services:
  - type: web
    name: n8n-automation-server
    plan: free
    runtime: docker
    dockerfile_path: Dockerfile # Tells Render to use the default root configuration
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_CONNECTION_STRING
        value: "postgres://user:pass@host:port/db"
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: N8N_PORT
        value: "10000"
